### PR TITLE
initial script refactor

### PR DESCRIPTION
**Pull request by azhou42**
changed point mass and ant scripts for now, any comments on the restructuring?

### CODE REVIEW

**Comment by katerakelly** [comment]
my changes apply only to point robot...btw it runs but the scale of things is off, the returns are ~ -200 and the z values are ~ 40...did we change a constant somewhere in the alg settings?

**Comment by azhou42** [comment]
I don't think I changed anything. Could it be due to reward scale being moved soemwhere where it happens in the logging?

**Comment by azhou42** [comment]
One other thing that might be nice to add is a default variant somewhere, and have each script only overwrite t he values it wants to change?

**Comment by katerakelly** [comment]
added the default variant, looking into the weird scaling now

**Comment by katerakelly** [comment]
alright, verified this looks correct when I run it. anything else?

**Comment by azhou42** [comment]
We just need to change the other launch scripts to match now.

**Comment by katerakelly** [comment]
I think it might be good to wait cause if we change arg names / merge the data sampling refactor, we'd have to change arg names in all the scripts...

**Comment by azhou42** [comment]
Alright let's just merge this in then?

**Comment by katerakelly** [comment]
I am rebasing it and then will merge

**Pull request closed without merging**
