### PR TITLE
refactor scripts further to use config dicts per exp

### PR DESCRIPTION
**Pull request by katerakelly**

### CODE REVIEW

**Comment by azhou42** [comment]
My preference for organizing this would just be to have a config.json for each file, then pass in the filename as an argument. I think it looks a bit more organized than the setup now, and we don't need to register configs or anything.

**Comment by katerakelly** [comment]
OK I don't really have a preference, so I switched to json.

**Comment by katerakelly** [comment]
lol why didn't I think of that XD

**Comment by azhou42** [comment]
looks good to me :)

**Pull request merged**
